// import type { NextPage } from 'next';
import Head from 'next/head';

function Home() {
  return (
    <>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>

      <main className="mx-auto max-w-4xl px-4 min-h-screen flex flex-col">
        <h1 className="m-auto w-full text-center text-2xl">
          Welcome to
          {' '}
          <a href="https://nextjs.org">Next.js!</a>
        </h1>
      </main>
    </>
  );
}

export default Home;
