import { Project } from './types';

const projects: Project[] = [
  {
    title: 'anonymous-message-board',
    demoUrl: '',
    srcUrl: 'https://github.com/juliencrn/anonymous-message-board',
    createdAt: '7/1/2020',
    tags: [
      'expressjs',
      'jest',
      'mongodb',
      'mongoose',
      'nodejs',
      'react',
      'typescript',
    ],
    excerpt: 'Last FreeCodeCamp backend excercise using Node Express MongoDB Typescript Jest & React',
  },
  {
    title: 'chat',
    demoUrl: '',
    srcUrl: 'https://github.com/juliencrn/chat',
    createdAt: '10/7/2021',
    tags: [
      'docker',
      'lerna',
      'mongodb',
      'nestjs',
      'react-router',
      'reactjs',
      'redux',
      'socket-io',
      'tailwindcss',
      'typescript',
    ],
    excerpt: 'Simple chat application to learn backend dev using JavaScript.',
  },
  {
    title: 'dotfiles',
    demoUrl: '',
    srcUrl: 'https://github.com/juliencrn/dotfiles',
    createdAt: '11/21/2020',
    tags: [
      'i3wm',
      'linux',
      'oh-my-zsh',
      'shell-script',
      'ubuntu',
      'vim',
      'vscode',
      'zsh',
    ],
    excerpt: 'Personal linux config',
  },
  {
    title: 'drum-machine',
    demoUrl: 'https://zz-drum-machine.netlify.com/',
    srcUrl: 'https://github.com/juliencrn/drum-machine',
    createdAt: '10/27/2019',
    tags: [
      'freecodecamp',
      'javascript',
      'react',
    ],
    excerpt: 'Front-end FreeCodeCamp project : Build a drum machine using React',
  },
  {
    title: 'eslint-config-test',
    demoUrl: '',
    srcUrl: 'https://github.com/juliencrn/eslint-config-test',
    createdAt: '11/20/2020',
    tags: [],
    excerpt: 'PoC of eslint config module',
  },
  {
    title: 'game-of-life',
    demoUrl: '',
    srcUrl: 'https://github.com/juliencrn/game-of-life',
    createdAt: '1/1/2022',
    tags: [
      'canvas',
      'js',
      'rust',
      'wasm',
      'webassembly',
    ],
    excerpt: 'A game-of-life implementation with Rust and WebAssembly.',
  },
  {
    title: 'gatsby-material-typescript-starter',
    demoUrl: 'https://gatsby-material-typescript-starter.netlify.app/',
    srcUrl: 'https://github.com/juliencrn/gatsby-material-typescript-starter',
    createdAt: '4/16/2020',
    tags: [
      'eslint',
      'gatsby',
      'material-ui',
      'prettier',
      'react',
      'typescript',
      'usetheme',
    ],
    excerpt: 'A simple starter using Typescript & Material-ui',
  },
  {
    title: 'gatsby-starter-mdx-themeui',
    demoUrl: '',
    srcUrl: 'https://github.com/juliencrn/gatsby-starter-mdx-themeui',
    createdAt: '8/9/2019',
    tags: [
      'eslint',
      'gatsby',
      'graphql',
      'mdx',
      'prettier',
      'react',
      'theme-ui',
    ],
    excerpt: 'A simple Gatsby starter powered by MDX and Theme UI',
  },
  {
    title: 'gatsby-typescript-starter',
    demoUrl: '',
    srcUrl: 'https://github.com/juliencrn/gatsby-typescript-starter',
    createdAt: '4/16/2020',
    tags: [
      'eslint',
      'gatsby',
      'prettier',
      'react',
      'typescript',
    ],
    excerpt: 'A simple blog starter using Typescript in front & back side with eslint & prettier',
  },
  {
    title: 'hello_grep',
    demoUrl: '',
    srcUrl: 'https://github.com/juliencrn/hello_grep',
    createdAt: '6/24/2021',
    tags: [
      'command-line',
      'filesystem',
      'rust',
    ],
    excerpt: 'Simplified grep clone to learn Rust - from "The Book"',
  },
  {
    title: 'kitten-challenge',
    demoUrl: '',
    srcUrl: 'https://github.com/juliencrn/kitten-challenge',
    createdAt: '5/14/2021',
    tags: [
      'firebase',
      'react',
      'react-native',
      'typescript',
    ],
    excerpt: 'React-native + Firebase app | WIP Project... abandoned',
  },
  {
    title: 'localhost',
    demoUrl: '',
    srcUrl: 'https://github.com/juliencrn/localhost',
    createdAt: '5/26/2019',
    tags: [
      'lamp',
      'localhost',
      'mamp',
      'php',
      'tachyons',
      'wamp',
    ],
    excerpt: 'Customize your localhost home page',
  },
  {
    title: 'markdown-previewer',
    demoUrl: '',
    srcUrl: 'https://github.com/juliencrn/markdown-previewer',
    createdAt: '10/27/2019',
    tags: [
      'emotion',
      'freecodecamp',
      'javascript',
      'markdown',
      'react',
      'rebass',
      'theme-ui',
    ],
    excerpt: 'FreeCodeCamp learning front-end project - Build a markdown previewer using React',
  },
  {
    title: 'mini-redis',
    demoUrl: '',
    srcUrl: 'https://github.com/juliencrn/mini-redis',
    createdAt: '12/26/2021',
    tags: [
      'runtime',
      'rust',
      'tokio',
    ],
    excerpt: 'Little project to learn how to build apps on top on Tokio, a Rust runtime.',
  },
  {
    title: 'netlify-status-page',
    demoUrl: 'https://netlify-status-page.netlify.app/',
    srcUrl: 'https://github.com/juliencrn/netlify-status-page',
    createdAt: '10/12/2020',
    tags: [
      'css',
      'github',
      'netlify',
      'react',
      'typescript',
    ],
    excerpt: 'Netlify status page',
  },
  {
    title: 'node-docker',
    demoUrl: '',
    srcUrl: 'https://github.com/juliencrn/node-docker',
    createdAt: '10/20/2021',
    tags: [
      'docker',
      'docker-compose',
      'mongodb',
      'nodejs',
    ],
    excerpt: 'Learning docker',
  },
  {
    title: 'oc-todo-node',
    demoUrl: '',
    srcUrl: 'https://github.com/juliencrn/oc-todo-node',
    createdAt: '1/14/2020',
    tags: [
      'express',
      'jquery',
      'nodejs',
      'socket-io',
    ],
    excerpt: 'Real time shared todo app using Node.js & Socket.io for OpenClassRoom learning project',
  },
  {
    title: 'oser-ecrire',
    demoUrl: '',
    srcUrl: 'https://github.com/juliencrn/oser-ecrire',
    createdAt: '4/29/2020',
    tags: [
      'blog',
      'gatsby',
      'jamstack',
      'lerna',
      'sanity-io',
      'typescript',
    ],
    excerpt: "The \"Oser Ecrire\"'s Blog",
  },
  {
    title: 'pomodoro-timer',
    demoUrl: 'https://fcc-pomodoro-timer.netlify.com',
    srcUrl: 'https://github.com/juliencrn/pomodoro-timer',
    createdAt: '11/8/2019',
    tags: [
      'bem',
      'freecodecamp',
      'jest',
      'react',
      'scss',
      'tdd',
    ],
    excerpt: 'FreeCodeCamp front-end project to learn test-driven development and BEM using react.js',
  },
  {
    title: 'portfolio (v2)',
    demoUrl: 'https://juliencaron.eu',
    srcUrl: 'https://github.com/juliencrn/portfolio',
    createdAt: '7/20/2019',
    tags: [
      'emotionjs',
      'gatsby',
      'graphql',
      'netlify',
      'portfolio',
      'react',
      'theme-ui',
      'typescript',
    ],
    excerpt: 'My portfolio using Gatsby.js as front-end and Prismic as CMS',
    featured: true,
  },
  {
    title: 'Legacy headless portfolio (v1)',
    demoUrl: '',
    srcUrl: 'https://github.com/juliencrn/portfolio-admin',
    createdAt: '9/5/2019',
    tags: [
      'headless-cms',
      'php',
      'wordpress',
    ],
    excerpt: 'WordPress as headless CMS for my personal Portfolio',
  },
  {
    title: 'random-quote-machine',
    demoUrl: 'https://junscuzzy.github.io/random-quote-machine/',
    srcUrl: 'https://github.com/juliencrn/random-quote-machine',
    createdAt: '10/22/2019',
    tags: [
      'bem',
      'freecodecamp',
      'hook',
      'javascript',
      'react',
      'scss',
    ],
    excerpt: 'FreeCodeCamp Front End Libraries Projects - Build a Random Quote Machine',
  },
  {
    title: 'React-calculator',
    demoUrl: 'https://junscuzzy.github.io/React-calculator/',
    srcUrl: 'https://github.com/juliencrn/React-calculator',
    createdAt: '4/22/2019',
    tags: [
      'javascript',
      'react',
    ],
    excerpt: 'Learning project',
  },
  {
    title: 'react-calculator-v2',
    demoUrl: '',
    srcUrl: 'https://github.com/juliencrn/react-calculator-v2',
    createdAt: '1/3/2020',
    tags: [
      'calculator',
      'freecodecamp',
      'material-ui',
      'react',
      'typescript',
    ],
    excerpt: 'FreeCodeCamp Frontend challenge - Calculator using react & TS',
  },
  {
    title: 'react-gallery',
    demoUrl: 'https://react-gallery.juliencaron.com/',
    srcUrl: 'https://github.com/juliencrn/react-gallery',
    createdAt: '6/25/2020',
    tags: [
      'material-ui',
      'pexels-api',
      'react',
      'redux',
      'tests',
      'typescript',
      'ux',
    ],
    excerpt: 'Learning front-end project : Skeleton > Blur Thumbnail > Image lazy-loading.',
  },
  {
    title: 'React-morpion',
    demoUrl: 'https://junscuzzy.github.io/React-morpion/',
    srcUrl: 'https://github.com/juliencrn/React-morpion',
    createdAt: '4/22/2019',
    tags: [
      'javascript',
      'react',
    ],
    excerpt: 'Learning project: Tic Tac Toe game using React.',
  },
  {
    title: 'react-pendu',
    demoUrl: 'https://react-pendu.netlify.com/',
    srcUrl: 'https://github.com/juliencrn/react-pendu',
    createdAt: '1/17/2020',
    tags: [
      'game',
      'material-ui',
      'openclassrooms',
      'react',
      'typescript',
    ],
    excerpt: 'React hanged game (in french) using React.',
  },
  {
    title: 'redux-todo',
    demoUrl: '',
    srcUrl: 'https://github.com/juliencrn/redux-todo',
    createdAt: '7/8/2019',
    tags: [
      'react',
      'react-hook',
      'redux',
      'tachyons',
    ],
    excerpt: 'To-do app to learn Redux',
  },
  {
    title: 'rusty-journal',
    demoUrl: '',
    srcUrl: 'https://github.com/juliencrn/rusty-journal',
    createdAt: '7/19/2021',
    tags: [
      'command-line',
      'diesel',
      'rust',
      'sqlite',
    ],
    excerpt: 'Learning project: A command line to-do app written in Rust.',
  },
  {
    title: 'spacedicks',
    demoUrl: 'http://spacedicks.xyz',
    srcUrl: 'https://github.com/juliencrn/spacedicks-contract',
    createdAt: '12/10/2021',
    tags: [
      'blockchain',
      'express',
      'ipfs',
      'nft',
      'mocha',
      'svg',
      'typescript',
      'web3',
      'solidity',
    ],
    excerpt: '10,000 unique NTFs with proof of ownership living on the Polygon blockchain and following the ERC-721 standard.',
    featured: true,
  },
  {
    title: 'sportigoo',
    demoUrl: 'https://sportigoo.fr/',
    srcUrl: '',
    createdAt: '10/30/2019',
    tags: [
      'gulp',
      'scss',
      'woocommerce',
      'wordpress',
    ],
    excerpt: 'Sportigoo.fr WordPress website',
  },
  {
    title: 'svelte-life-in-weeks',
    demoUrl: 'https://life-in-weeks.juliencaron.com/',
    srcUrl: 'https://github.com/juliencrn/svelte-life-in-weeks',
    createdAt: '7/25/2021',
    tags: [
      'svelte',
      'tailwindcss',
      'typescript',
    ],
    excerpt: 'Little front-end pet project to discover Svelte. Are you curious to see your whole life in weeks?',
  },
  {
    title: 'telegram-rsi-bot',
    demoUrl: '',
    srcUrl: 'https://github.com/juliencrn/telegram-rsi-bot',
    createdAt: '11/20/2021',
    tags: [
      'bot',
      'cryptocurrency',
      'finance',
      'heroku',
      'rsi',
      'stocks',
      'telegram-bot',
      'yahoo-finance',
    ],
    excerpt: 'Send me the price and the Relative Strength Index (RSI) for some crypto assets, stocks and indexes',
  },
  {
    title: 'tetris',
    demoUrl: '',
    srcUrl: 'https://github.com/juliencrn/tetris',
    createdAt: '4/4/2020',
    tags: [
      'canvas',
      'canvas-game',
      'react',
      'react-hooks',
      'react-redux',
      'redux-toolkit',
      'theme-ui',
      'typescript',
    ],
    excerpt: 'Build a Tetris Game using HTML5 Canvas & React + Redux ',
  },
  {
    title: 'the-algorithm-challenge',
    demoUrl: 'https://www.freecodecamp.org/learn/',
    srcUrl: 'https://github.com/juliencrn/the-algorithm-challenge',
    createdAt: '1/6/2021',
    tags: [
      'algorithms',
      'data-structures',
      'freecodecamp',
      'project-euler',
      'rosetta-code',
      'rust',
      'tdd',
      'typescript',
    ],
    excerpt: "Let's practice the algorithms and data-structures using TDD and written in Typescript and Rust (The exercises are from FreeCodeCamp)",
  },
  {
    title: 'ts-blockchain-api',
    demoUrl: '',
    srcUrl: 'https://github.com/juliencrn/ts-blockchain-api',
    createdAt: '4/12/2020',
    tags: [
      'api-rest',
      'axios',
      'blockchain',
      'eslint',
      'express',
      'typescript',
    ],
    excerpt: 'Learning project: Implement a very simple blockchain, served in a REST API and made with Typescript OOP & Express.js',
  },
  {
    title: 'url-shortener',
    demoUrl: '',
    srcUrl: 'https://github.com/juliencrn/url-shortener',
    createdAt: '11/27/2019',
    tags: [
      'freecodecamp',
      'javascript',
      'mongodb',
      'mongoose',
      'nodejs',
      'rest-api',
    ],
    excerpt: 'FreeCodeCamp Micro-services with NodeJS: Build an url shortener (like Bitly)',
  },
  {
    title: 'usehooks-ts',
    demoUrl: 'https://usehooks-ts.com/',
    srcUrl: 'https://github.com/juliencrn/usehooks-ts',
    createdAt: '4/16/2020',
    tags: [
      'gatsby',
      'hooks',
      'material-ui',
      'mdx',
      'react',
      'react-hooks',
      'reactjs',
      'typescript',
    ],
    excerpt: 'Open-source: React hook library, ready to use, written in Typescript.',
    featured: true,
  },
  {
    title: 'voting-dapp',
    demoUrl: '',
    srcUrl: 'https://github.com/juliencrn/voting-dapp',
    createdAt: '8/6/2021',
    tags: [
      'dapp',
      'react',
      'solidity',
      'truffle',
      'web3',
    ],
    excerpt: 'A basic voting dapp (decentralized application) written in Solidity & React.',
  },
  {
    title: 'whiteboard',
    demoUrl: 'https://recoil-whiteboard.netlify.app/',
    srcUrl: 'https://github.com/juliencrn/whiteboard',
    createdAt: '2/19/2021',
    tags: [
      'dracula',
      'react',
      'react-konva',
      'recoil',
      'typescript',
    ],
    excerpt: 'Experimental learning project: Building a web whiteboard to draw mind-maps or mock-ups',
  },
  {
    title: 'wordpress-to-ndjson',
    demoUrl: '',
    srcUrl: 'https://github.com/juliencrn/wordpress-to-ndjson',
    createdAt: '4/30/2020',
    tags: [
      'cli',
      'minimist',
      'ndjson',
      'nodejs',
      'sanity-io',
      'typescript',
      'wordpress',
    ],
    excerpt: 'CLI tool that fetch WordPress data to produce ndjson files for sanity.io importation',
  },
  {
    title: 'wp-search-n-replace',
    demoUrl: 'https://wordpress-db-search-and-replace.netlify.com/',
    srcUrl: 'https://github.com/juliencrn/wp-search-n-replace',
    createdAt: '12/3/2019',
    tags: [
      'dracula',
      'formik',
      'material-ui',
      'react',
      'search-and-replace',
      'sql',
      'wordpress',
    ],
    excerpt: 'SQL query generator to search & replace URLs during website transfert',
  },
];

export default projects;
